CC = g++
CFLAGS = -m32 -march=native -O3 -std=c++20 -DNDEBUG -pthread -I./src
LDFLAGS = -lbcrypt 
SRC = main.cpp threadpool.cpp locker.cpp api.cpp logs.cpp memory.cpp global_parameters.cpp CommandParser.cpp pathsystem.cpp \
filesystem/meta.cpp filesystem/crypt.cpp filesystem/rsa.cpp filesystem/hash.cpp filesystem/names.cpp filesystem/wipe.cpp \
crypto/chacha20/laced.cpp crypto/sha/sha256.cpp crypto/aes/aes256.cpp crypto/base64/base64.cpp crypto/rsa/rsa.cpp

SRCS = $(addprefix src/,$(SRC))
OBJ = $(SRCS:.cpp=.o)
EXEC = laced

all: $(EXEC)

$(EXEC): $(OBJ)
	$(CC) $(OBJ) -o $(EXEC) $(LDFLAGS)

%.o: %.cpp
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(EXEC)
