CC = g++
CFLAGS = -m32 -march=native -O3 -std=c++20 -DNDEBUG
SRC = pathsystem.cpp memory.cpp global_parameters.cpp main.cpp locker.cpp filesystem.cpp ChaCha20/laced.cpp
OBJ = $(SRC:.cpp=.o)
EXEC = laced

all: $(EXEC)

$(EXEC): $(OBJ)
	$(CC) $(OBJ) -o $(EXEC)

%.o: %.cpp
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(EXEC)
